name:                aoc2025
version:             0.1.0.0
github:              "JonathanFraser/aoc2025"
license:             MIT
author:              "Jonathan Fraser"
maintainer:          "jonathanfras@gmail.com"
copyright:           "2025 Jonathan Fraser"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aoc2025#readme>

dependencies:
- base >= 4.7 && < 5
- text
- file-embed
- bytestring 
- template-haskell

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  aoc: 
    main: Main.hs
    source-dirs: aoc
    ghc-options: 
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2025
    - text
    - optparse-applicative

tests:
  aoc2025-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2025
